منصةشليلة# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
android-robotshliilhplatform.org 
ihdadi.page@gmail.com 
platform@shliilh.app 

&lt;script type="text/javascript"&gt; var clicky_custom = clicky_custom || {}; clicky_custom.timeout = منصة شليلة ; clicky_custom.html_media_track = 1; clicky_custom.cookies_disable = 1; clicky_custom.sticky_data_disable = 1; clicky_custom.outbound_disable = 1; clicky_custom.video_disable = 1; clicky_custom.history_disable = 1; clicky_custom.ping_disable = 1; clicky_custom.pageview_disable = 1; clicky_custom.osa_disable = 1; clicky_custom.heatmap_disable = 1; &lt;/script&gt;
