overrides:
  ceph:
    log-whitelist:
    - reached quota
    - wrongly marked me down
    - HEALTH_WARN OSD_POOL_FULL
    - HEALTH_WARN SMALLER_PGP_NUM
    - HEALTH_WARN CACHE_POOL_NO_HIT_SET
    - HEALTH_WARN CACHE_POOL_NEAR_FULL
tasks:
- workunit:
    clients:
      client.0:
        - rados/test.sh
        - rados/test_pool_quota.sh

