# see http://tracker.ceph.com/issues/20360 and http://tracker.ceph.com/issues/18126
os_type: centos

tasks:
- install:
    flavor: notcmalloc
- ceph:
- openssl_keys:
- dnsmasq:
    client.0:
      s3.: client.0
      s3-website.: client.1
- rgw:
    client.0:
      port: 80
      dns-name: s3.
    client.1:
      port: 80
      dns-s3website-name: s3-website.

overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw enable static website: True
      client.0:
        rgw lc debug interval: 10
      client.1:
        rgw enable apis: s3website
    rgw:
      client.0:
        valgrind: [--tool=memcheck, --max-threads=1024] # http://tracker.ceph.com/issues/25214
      client.1:
        valgrind: [--tool=memcheck, --max-threads=1024] # http://tracker.ceph.com/issues/25214
