os_type: centos   # xenial valgrind buggy, see http://tracker.ceph.com/issues/18126
tasks:
- install:
    flavor: notcmalloc
    debuginfo: true
- ceph:
- dnsmasq:
    client.0:
      - client.0.ceph.com
- rgw:
    client.0:
      valgrind: [--tool=memcheck]
- s3tests:
    client.0:
      git_remote: git://github.com/theanalyst/
      force-branch: abs-urls
      calling_format: subdomain
      rgw_host_override: client.0.ceph.com
      extra_attrs: '!fails_with_subdomain'
overrides:
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw lc debug interval: 10
        rgw dns name: client.0.ceph.com
