overrides:
   ceph_ansible:                                                                                                                                                 
      vars:                                                                                                                                                       
         ceph_conf_overrides: 
            log-whitelist:
            - reached quota
            - wrongly marked me down
            - objects unfound and apparently lost

tasks:
- thrashosds:
    chance_pgnum_grow: 2
    chance_pgpnum_fix: 1
    timeout: 1200
- workunit:
    clients:
      client.0:
      - rados/test.sh
