tasks:
- install:
- exec:
    mon.b:
    - sudo systemctl stop ntpd || sudo /etc/init.d/ntp stop
    - date -u -s @$(expr $(date -u +%s) + 10)
- full_sequential_finally:
  - exec:
      mon.b:
        - sudo systemctl start ntpd || sudo /etc/init.d/ntp start
- ceph:
    wait-for-healthy: false
    log-whitelist:
    - slow request
    - .*clock.*skew.*
    - clocks not synchronized
    - overall HEALTH_
    - \(MON_CLOCK_SKEW\)
    - \(MGR_DOWN\)
    - \(PG_
    - No standby daemons available
- mon_clock_skew_check:
    expect-skew: true
