---
name: "Pull Request Checklist"
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
jobs:
  pr_checklist:
    runs-on: ubuntu-latest
    name: Verify
    steps:
      - name: Action
        id: checklist
        uses: ceph/ceph-pr-checklist-action@main
