name: Check PR dependencies
on: [pull_request_target]
permissions:
  contents: read

jobs:
  check_dependencies:
    permissions:
      issues: read  # for gregsdennis/dependencies-action to check issues for dependencies
      pull-requests: read  # for gregsdennis/dependencies-action to check PRs for dependencies
    runs-on: ubuntu-latest
    name: Check PR Dependencies
    steps:
    - uses: gregsdennis/dependencies-action@80b5ffec566913b1494d5a8577ab0d60e476271d
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
